# Generated by Django 3.0.2 on 2023-03-30 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201008_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=0, max_length=50)),
                ('cname', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
