# Generated by Django 3.0.2 on 2023-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('qualifications', models.CharField(max_length=800)),
                ('requirements', models.CharField(max_length=800)),
                ('responsibilities', models.CharField(max_length=800)),
                ('email', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
