# Generated by Django 4.1.3 on 2022-11-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_followerscount_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
