# Generated by Django 4.1.3 on 2022-11-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
