# Generated by Django 4.1.3 on 2022-11-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='twelfth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ug',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
