# Generated by Django 4.1.3 on 2022-11-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_pg_profile_tenth_profile_twelfth_profile_ug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
