# Generated by Django 4.1.3 on 2023-02-27 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenth',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twelfth',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ug',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
    ]
