# Generated by Django 4.1.7 on 2023-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='responsibilities',
            field=models.CharField(max_length=100),
        ),
    ]
