# Generated by Django 4.1.7 on 2023-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_jobposting_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='id',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='jid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
