# Generated by Django 4.1.7 on 2023-03-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_jobposting_id_jobposting_jid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='jid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
